var food = {
  0:['images/food/Cake.png','这是一个蓝色的蛋糕，上面有三根蜡烛'],
  1:['images/food/Apple.png','这是一个红色的苹果，吃起来甜甜的'],
  2:['images/food/Cheese Slice.png','这是一块芝士，上面有好多小洞'],
  3:['images/food/French fries.png','这是薯条，吃起来脆脆的，咸咸的'],
  4:['images/food/Ice cream.png','这是一个粉红色的甜筒，吃起来凉凉的'],
  5:['images/food/Orange Juice.png','这是一瓶橙色的橘子汁饮料，喝起来酸酸甜甜'],
  6:['images/food/Watermelon.png','这是西瓜，里面有好多黑色的小籽'],
  7:['images/food/Waffles.png','这是华夫饼，吃起来又香又甜'],
  8:['images/food/Bacon.png','这是培根，吃起来咸咸的还有浓郁的烟熏味'],
  9:['images/food/Bananas.png','这是一串香蕉，里面有四根香蕉'],
  10:['images/food/Cheeseburger.png','这是一个汉堡，里面有芝士蔬菜牛肉和面包'],
  11:['images/food/Chilli pepper.png','这是辣椒，小心它很辣哟！'],
};

var month = {
  0:['images/month/January.png','一月梅花香又香'],
  1:['images/month/February.png','二月兰花盆里装'],
  2:['images/month/March.png','三月桃花红千里'],
  3:['images/month/April.png','四月蔷薇靠短墙'],
  4:['images/month/May.png','五月石榴红似火'],
  5:['images/month/June.png','六月荷花满池塘'],
  6:['images/month/July.png','七月栀子头上戴'],
  7:['images/month/Aug.png','八月桂花满枝香'],
  8:['images/month/Sept.png','九月菊花初开放'],
  9:['images/month/Oct.png','十月芙蓉正上妆'],
  10:['images/month/Nov.png','十一月水仙案上供'],
  11:['images/month/Dec.png','十二月腊梅雪里香'],
};

var object = {
  0:['images/liwu.png','这是一个礼物，看上去很不错'],
  1:['images/object/bag.png','这是一个书包，里面装着课本'],
  2:['images/object/ruler.png','这是一把尺子，可以用来衡量距离'],
  3:['images/object/tape.png','这是一个磁带，里面有着动听的音乐'],
  4:['images/object/tellurion.png','这是一个地球仪，可以在上面看到其他的国家'],
  5:['images/object/abacus.png','这是一个算盘，可以用来算数'],
  6:['images/object/scissor.png','这是一把剪刀，可以用来剪纸'],
  7:['images/object/calculator.png','这是一个计算器，可以用来计算难题'],
  8:['images/object/Pen.png','这是一支钢笔，可以用来写字'],
  9:['images/object/camera.png','这是一个相机，可以用来拍照'],
  10:['images/object/palette.png','这是一个画板，可以混合不同颜色'],
  11:['images/object/plane.png','这是一架飞机，可以飞往远方'],
  12:['images/object/briefcase.png','这是一个公文包，里面装了很多文件'],
  13:['images/object/computer.png','这是一个电脑，里面有很多有趣的游戏'],
  14:['images/object/clock.png','这是一个闹钟，可以提醒人们'],
  15:['images/object/flashlight.png','这是一个手电筒，可以照亮前方的路'],
  16:['images/object/goggle.png','这是一个泳镜，可以带上它去潜水'],
  17:['images/object/swimring.png','这是一个游泳圈，可以防止人们落水'],
  18:['images/object/oxygenbottle.png','这是一个氧气瓶，为潜水提供氧气'],
};